name: Build and Deploy API to GCP

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build, Analyze, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Write GCP Service Account Key to File
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 --decode > ${HOME}/gcloud-service-key.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:${{ github.sha }} .

      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:${{ github.sha }}

      - name: Set short SHA for template
        id: set-short-sha
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Delete Old Instance Template if Exists
        run: |
          TEMPLATE_NAME="container-template-fastapi-${{ env.SHORT_SHA }}"
          gcloud compute instance-templates delete $TEMPLATE_NAME --quiet || true

      - name: Create New Instance Template with Updated Container Image
        run: |
          TEMPLATE_NAME="container-template-fastapi-${{ env.SHORT_SHA }}"
          gcloud compute instance-templates create-with-container $TEMPLATE_NAME \
            --machine-type=e2-medium \
            --boot-disk-size=10GB \
            --boot-disk-type=pd-standard \
            --container-image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:${{ github.sha }} \
            --container-env ENV=production,DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --tags=back-instances \
            --quiet

      - name: Update Managed Instance Group with New Template
        run: |
          ZONE="us-central1-c"
          INSTANCE_GROUP="blogapp-back"  # Replace with your instance group name
          TEMPLATE_NAME="container-template-fastapi-${{ env.SHORT_SHA }}"
          gcloud compute instance-groups managed rolling-action start-update $INSTANCE_GROUP \
            --version=template=$TEMPLATE_NAME \
            --zone=$ZONE --quiet
